name: Bug Report
description: Create a report to help us improve ZeroLimit
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your system and setup.
      value: |
        - OS:
        - ZeroLimit version:
        - CLIProxyAPI version:
        - Client(s) (e.g., Claude Code CLI, Cursor):
        - Network (e.g., Home network, Corporate VPN):
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: What did you do?
      placeholder: |
        1. Install and start CLIProxyAPI.
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: Add any other context about the problem here. Screenshots or console logs are helpful.
    validations:
      required: false
